// <auto-generated />
using System;
using GestorAssinaturas.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestorAssinaturas.Infraestrutura.Migrations
{
    [DbContext(typeof(GestorAssinaturasDbContext))]
    [Migration("20260805213744_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestorAssinaturas.Dominio.Assinaturas.Assinatura", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("DataDeCancelamentoAgendado")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataDeInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataDeTerminoDoTrial")
                        .HasColumnType("date");

                    b.Property<Guid>("IdentificadorDoCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdentificadorPlano")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoCliente");

                    b.HasIndex("IdentificadorPlano");

                    b.ToTable("Assinaturas", (string)null);
                });

            modelBuilder.Entity("GestorAssinaturas.Dominio.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Identificador");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("GestorAssinaturas.Dominio.Faturas.Fatura", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataDeVencimento")
                        .HasColumnType("date");

                    b.Property<Guid>("IdentificadorDaAssinatura")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDaAssinatura");

                    b.ToTable("Faturas", (string)null);
                });

            modelBuilder.Entity("GestorAssinaturas.Dominio.Planos.Plano", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CicloDeCobranca")
                        .HasColumnType("int")
                        .HasColumnName("CicloDeCobranca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PeriodoDeTrialEmDias")
                        .HasColumnType("int");

                    b.HasKey("Identificador");

                    b.ToTable("Planos", (string)null);
                });

            modelBuilder.Entity("GestorAssinaturas.Dominio.Assinaturas.Assinatura", b =>
                {
                    b.HasOne("GestorAssinaturas.Dominio.Planos.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("IdentificadorPlano")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("GestorAssinaturas.Dominio.Faturas.Fatura", b =>
                {
                    b.OwnsOne("GestorAssinaturas.Dominio.ObjetosDeValor.Dinheiro", "Valor", b1 =>
                        {
                            b1.Property<Guid>("FaturaIdentificador")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Moeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Valor");

                            b1.HasKey("FaturaIdentificador");

                            b1.ToTable("Faturas");

                            b1.WithOwner()
                                .HasForeignKey("FaturaIdentificador");
                        });

                    b.Navigation("Valor")
                        .IsRequired();
                });

            modelBuilder.Entity("GestorAssinaturas.Dominio.Planos.Plano", b =>
                {
                    b.OwnsOne("GestorAssinaturas.Dominio.ObjetosDeValor.Dinheiro", "Preco", b1 =>
                        {
                            b1.Property<Guid>("PlanoIdentificador")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Moeda")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PrecoMoeda");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PrecoValor");

                            b1.HasKey("PlanoIdentificador");

                            b1.ToTable("Planos");

                            b1.WithOwner()
                                .HasForeignKey("PlanoIdentificador");
                        });

                    b.Navigation("Preco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
