<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>GestorAssinaturas.Infraestrutura</RootNamespace>
    <AssemblyName>GestorAssinaturas.Infraestrutura</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestorAssinaturas.Aplicacao\GestorAssinaturas.Aplicacao.csproj" />
  </ItemGroup>

</Project>
